# Default values for ocp-route.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  clusterType: "openshift"

clusterType: "ocp4"

nameOverride: ""

targetPort: "9000"

app: "sonarqube"
serviceName: "sonarqube"
termination: edge
insecurePolicy: Redirect